language: node_js

before_script:
  - npm install -g gulp-cli

node_js:
  - "7"
  - "node"

sudo: false

deploy: 
  provide: npm
  email: "stevekent55@me.com"
  api_key: "bd16e4a7-4919-4ff7-b547-2213546ba65e"
